server:
  port: 84
spring:
  application:
    name: cloudalibaba-consumer-order
  cloud:
    nacos:
      discovery:
        #Nacos注册中心地址
        server-addr: 192.168.174.131:1111
    sentinel:
      transport:
        #配置Sentinel dashboard地址
        dashboard: 192.168.174.131:8080
        #默认8719端口,假如被占用会自动从8719开始依次+1扫描,直至找到未被占用的端口
        port: 8719
      datasource:
        dsl:
          nacos:
            server-addr: 192.168.174.131:1111
            dataId: cloudalibaba-consumer-order
            groupId: DEFAULT_GROUP
            data_type: json
            rule-type: flow

management:
  endpoints:
    web:
      exposure:
        include: "*"

#消费者将要去访问的微服务名称(注册成功进nacos的微服务提供者)
#service-url:
#  nacos-user-service: http://nacos-payment-provider

# 对 Feign 的支持
feign:
  sentinel:
    enabled: true